version: 1.0
runtime: python3
build:
  commands:
    pre-build:
      - pip install --upgrade pip
    build:
      - pip install -r requirements.txt
run:
  command: python app.py
  network:
    port: 5000
    env: PORT
