services:
  - type: web
    name: insta-dm-sender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    repo: https://github.com/miramul/instaDM.git  # 実際のリポジトリURLに修正
    branch: main
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
